/* v9.4 customer journey and evidence guards. */
function regionEvidence(name){return EVIDENCE.filter(e=>e.region===name||(e.region||'').split('·').map(x=>x.trim()).includes(name))}
const gateKeys={culture:'culture_arts',nomad:'nomad_work',pet:'pet_friendly',benefit:'benefits',price:'price_value'};
function categoryReady(name,category){const key=gateKeys[category],rule=GATES.rules?.[key];if(!rule)return false;return GATES.regions?.[name]?.[key]?.ready===true&&Object.entries(rule.required).every(([c,min])=>regionEvidence(name).filter(e=>e.category===c&&liveEvidence(e)).length>=min)}
function categoryText(name,category){return categoryReady(name,category)?'근거 기준 충족':'원문 확인 · 근거 부족'}
function evidenceFactor(region,theme){const cat={culture:'culture',nomad:'nomad',pet:'pet',benefit:'benefit',settlement:'settlement',nature:'nature',wellness:'monthly',community:'community'}[theme];const ev=regionEvidence(region).filter(e=>e.category===cat&&liveEvidence(e));if(!ev.length)return 0;if(gateKeys[theme]&&!categoryReady(region,theme))return 0;return 1}
function evidenceAgeState(date){const t=Date.parse(date+'T00:00:00+09:00');const days=(Date.now()-t)/86400000;if(!Number.isFinite(t)||days<0)return {label:'미확인',factor:0,cls:''};if(days<=14)return {label:'최신',factor:1,cls:'ok'};if(days<=30)return {label:'재확인',factor:.9,cls:'dev'};return {label:'만료',factor:0,cls:''}}
function switchPanel(id){if(!['home','regions','rankings','monthly','mystay'].includes(id))return;$$('.panel').forEach(p=>p.classList.toggle('active',p.id===id));$$('.nav button').forEach(b=>{b.classList.toggle('active',b.dataset.panel===id);b.setAttribute('aria-current',b.dataset.panel===id?'page':'false')});if(id==='mystay')renderSavedHub();if(id==='monthly'){renderProgramDesk();renderVerifiedNotices();}const heading=$(`#${id} h1`);if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true})}scrollTo({top:0,behavior:'instant'})}
let regionFilter={province:'전체',query:''},eventFilter='전체',activeRegion=null;
function regionActions(name){const n=escapeHTML(name);return `<div class="row-actions"><button class="btn" data-region="${n}">상세 보기</button><button class="btn" data-save="${n}" aria-pressed="${state.saved.includes(name)}">${state.saved.includes(name)?'저장 해제':'MY MONTH 저장'}</button><button class="btn" data-compare="${n}" aria-pressed="${state.compare.includes(name)}">${state.compare.includes(name)?'비교에서 빼기':'비교 담기'}</button></div>`}
function renderRegions(province=regionFilter.province,query=regionFilter.query){regionFilter={province,query};const rows=REGIONS.filter(r=>(province==='전체'||r.province===province)&&(!query||r.name.includes(query)||r.province.includes(query)));$('#regionGrid').innerHTML=rows.map(r=>`<article class="region"><small>${escapeHTML(r.province)}</small><h2>${escapeHTML(r.name)}</h2><p>${r.strengths.map(escapeHTML).join(' · ')}</p><p class="small">생활비: ${escapeHTML(r.cost)} · 반려견: ${categoryText(r.name,'pet')}</p>${regionActions(r.name)}</article>`).join('')||'<p>상세 지역에 일치하는 결과가 없습니다. 전체 89개 지역에서 확인하세요.</p>';$$('#regions .filters .chip').forEach(b=>b.classList.toggle('active',b.textContent===province))}
function renderAll89(query=''){$('#all89Grid').innerHTML=ALL89.filter(r=>!query||r.name.includes(query)||r.province.includes(query)||r.display_name.includes(query)).map(r=>`<article class="region"><small>${escapeHTML(r.province)}</small><h3>${escapeHTML(r.name)}</h3><p>${resolveRegion(r.province+' '+r.name)?'상세 근거 제공':'상세 데이터 수집 예정 · 추천 판정 보류'}</p><button class="btn" data-region="${escapeHTML(r.province+' '+r.name)}">지역 확인</button></article>`).join('')||'<p>일치하는 지역이 없습니다.</p>'}
function resolveRegion(name){return REGIONS.find(r=>r.name===name)||REGIONS.find(r=>name===r.name+'군'||name===r.name+'시'||name===r.province+' '+r.name+'군'||name===r.province+' '+r.name+'시')}
function openRegion(name){const r=resolveRegion(name);activeRegion=r?.name||name;switchPanel('regions');const box=$('#regionDetail');box.hidden=false;const ev=regionEvidence(activeRegion);box.innerHTML=`<button class="text-link" id="closeRegion">← 지역 목록으로</button><div class="kicker">지역 상세</div><h1>${escapeHTML(activeRegion)}</h1><p>${r?r.strengths.map(escapeHTML).join(' · '):'89개 지역 색인 · 상세 근거 수집 예정'}</p>${r?regionActions(r.name):''}<div class="row-actions"><button class="btn" onclick="switchPanel('rankings')">비교 보기 →</button><button class="btn" onclick="switchPanel('monthly')">NOW 공고·일정 →</button><button class="btn" onclick="switchPanel('mystay')">MY MONTH →</button></div><p>지역의 생활 근거와 프로그램 지원 자격은 별도입니다. 아래 기록은 실시간 확인 결과가 아니며 방문 전 원문을 확인하세요.</p><h2>확인된 출처 ${ev.length}건</h2>${ev.length?ev.map(sourceCard).join(''):'<p>등록된 상세 근거가 없습니다. 비용·동반 가능 여부는 원문 확인이 필요합니다.</p>'}`;$('#closeRegion').onclick=()=>{box.hidden=true;activeRegion=null;$('#regionGrid').scrollIntoView()};box.querySelector('h1').tabIndex=-1;box.querySelector('h1').focus({preventScroll:true});scrollTo(0,0)}
function toggleSave(name){state.saved=state.saved.includes(name)?state.saved.filter(x=>x!==name):[...state.saved,name];save();refreshSaved();toast(state.saved.includes(name)?`${name} 저장했어요.`:'저장 해제했어요.')}
function saveRegionToMonth(name){if(!state.saved.includes(name))state.saved.push(name);save();switchPanel('mystay')}
function toggleCompare(name){if(state.compare.includes(name))state.compare=state.compare.filter(x=>x!==name);else if(state.compare.length<3)state.compare.push(name);else return toast('비교는 최대 3곳입니다. 비교 화면에서 먼저 빼주세요.');save();refreshSaved();toast(`비교 ${state.compare.length}/3곳`)}
function refreshSaved(){renderRegions();renderCompare();renderSavedHub();$$('[data-save]').forEach(b=>{b.textContent=state.saved.includes(b.dataset.save)?'저장 해제':'MY MONTH 저장';b.setAttribute('aria-pressed',state.saved.includes(b.dataset.save))});$$('[data-compare]').forEach(b=>{b.textContent=state.compare.includes(b.dataset.compare)?'비교에서 빼기':'비교 담기';b.setAttribute('aria-pressed',state.compare.includes(b.dataset.compare))})}
function renderCompare(){const rows=state.compare.map(resolveRegion).filter(Boolean);$('#compareTable').innerHTML=rows.length?`<caption>저장한 지역 ${rows.length}곳 · 근거 기준 비교</caption><thead><tr><th scope="col">확인 항목</th>${rows.map(r=>`<th scope="col">${escapeHTML(r.name)}${regionActions(r.name)}</th>`).join('')}</tr></thead><tbody>${[['문화','culture'],['노마드','nomad'],['반려견','pet'],['혜택','benefit']].map(([label,key])=>`<tr><th scope="row">${label}</th>${rows.map(r=>`<td>${categoryText(r.name,key)}</td>`).join('')}</tr>`).join('')}<tr><th scope="row">생활비</th>${rows.map(r=>`<td>${escapeHTML(r.cost)} · 원문 확인</td>`).join('')}</tr></tbody>`:'<caption>비교할 지역을 최대 3곳 담으세요.</caption><tbody><tr><td><button class="btn" onclick="switchPanel(\'regions\')">지역 둘러보기 →</button></td></tr></tbody>'}
function eventKey(e){return [e.region,e.title,e.date].join('|')}
function toggleEvent(key){state.events=state.events.includes(key)?state.events.filter(x=>x!==key):[...state.events,key];save();renderEvents();renderSavedHub();toast('일정 저장 목록을 갱신했어요.')}
function renderEvents(filter=eventFilter){eventFilter=filter;const rows=EVENTS.filter(e=>filter==='전체'||e.type.includes(filter)||e.tags.includes(filter));$('#eventGrid').innerHTML=rows.map(e=>`<article class="event"><small>${escapeHTML(e.region)} · ${escapeHTML(e.date)} (2026 기록)</small><h3>${escapeHTML(e.title)}</h3><p>${escapeHTML(e.price)}</p><p class="small">운영·잔여석은 원문 재확인</p><div class="row-actions"><button class="btn" data-event="${escapeHTML(eventKey(e))}" aria-pressed="${state.events.includes(eventKey(e))}">${state.events.includes(eventKey(e))?'일정 저장 해제':'일정 저장'}</button><button class="btn" data-region="${escapeHTML(e.region)}">지역·출처 보기</button></div></article>`).join('')||'<p>해당 분류의 일정이 없습니다.</p>';$$('#monthly .filters .chip').forEach(b=>b.classList.toggle('active',b.textContent===filter))}
function savedPlans(){const a=readValidated('lm_saved_plans',[]);return Array.isArray(a)?a.filter(p=>p&&p.top&&typeof p.top.region==='string'&&Array.isArray(p.plan)&&(!p.themes||Array.isArray(p.themes))):[]}
function renderSavedHub(){const box=$('#savedHub');if(!box)return;const events=EVENTS.filter(e=>state.events.includes(eventKey(e)));box.innerHTML=`<h2>지역 ${state.saved.length}</h2>${state.saved.length?state.saved.map(n=>`<article class="card"><h3>${escapeHTML(n)}</h3>${regionActions(n)}</article>`).join(''):'<p>아직 저장한 지역이 없습니다. 추천이나 지역 상세에서 담아보세요.</p><button class="btn" onclick="switchPanel(\'home\')">추천 시작하기 →</button>'}<h2>일정 ${events.length}</h2>${events.map(e=>`<article class="card"><h3>${escapeHTML(e.title)}</h3><p>${escapeHTML(e.region)} · ${escapeHTML(e.date)}</p><button class="btn" data-event="${escapeHTML(eventKey(e))}">일정 저장 해제</button><button class="btn" data-region="${escapeHTML(e.region)}">지역 상세</button></article>`).join('')||'<p>NOW에서 관심 일정을 담아보세요.</p>'}<h2>추천 ${savedPlans().length}</h2>${savedPlans().map((p,i)=>`<article class="card"><h3>${escapeHTML(p.top.region)} · ${escapeHTML(p.days)}일</h3><p>${(p.themes||[]).map(t=>escapeHTML(themeLabel(t)||t)).join(' · ')}</p><button class="btn" data-region="${escapeHTML(p.top.region)}">지역 상세</button><button class="btn" data-plan-remove="${i}">추천 삭제</button></article>`).join('')||'<p>추천 결과에서 ‘추천 저장’을 눌러보세요.</p>'}`}
function runReco(){const days=+$('#stayDays').value,budget=$('#budget').value;const ranked=REGIONS.map(r=>({r,s:recoScore(r,days,budget)})).filter(x=>x.s>0).sort((a,b)=>b.s-a.s);if(!ranked.length){invalidateRecommendation('선택한 조건에 반영할 최신 근거가 부족합니다. 지역 목록에서 출처를 확인하거나 조건을 바꿔 주세요.');return}currentRecommendation={version:APP_VERSION,created_at:new Date().toISOString(),days,budget,themes:[...selectedThemes],top:{region:ranked[0].r.name},alternatives:ranked.slice(1,3).map(x=>x.r.name),plan:plan(days)};$('#programDays').value=String(days);$('#recoResult').innerHTML=`<h2>${days}일 · ${selectedThemes.map(themeLabel).join(' + ')}</h2><p>예산 성향: ${{save:'가성비',balanced:'균형',experience:'경험 우선'}[budget]}. 근거가 있는 후보 ${Math.min(ranked.length,3)}곳입니다. 기존 베타 지표를 기간·취향에 따라 정렬한 탐색 후보입니다. 지원 가능 여부나 실측 만족도를 뜻하지 않습니다.</p>${ranked.slice(0,3).map((x,i)=>`<article class="card"><h3>${i+1}. ${escapeHTML(x.r.name)}</h3><p>${x.r.strengths.map(escapeHTML).join(' · ')}</p><p class="small">${selectedThemes.map(t=>`${themeLabel(t)}: ${evidenceFactor(x.r.name,t)>0?'근거 반영':'근거 부족 · 테마 가점 제외'}`).join(' / ')}</p>${regionActions(x.r.name)}</article>`).join('')}<p>기간은 단기 문화·탐색과 장기 업무·정착 지표의 비중에 반영됩니다. 비용 미확인 지역은 가격 가점이 없습니다.</p><button class="btn" onclick="switchPanel('rankings')">담은 지역 비교 →</button><button class="btn" onclick="switchPanel('mystay')">MY MONTH →</button>`;$('#recoResult').setAttribute('aria-live','polite');['savePlan','exportPlan','exportPlanJson'].forEach(id=>$('#'+id).disabled=false)}
function saveCurrentPlan(){if(!currentRecommendation)return toast('먼저 추천을 실행하세요.');const rows=savedPlans();const key=p=>JSON.stringify([p.days,p.budget,p.themes,p.top]);if(!rows.some(p=>key(p)===key(currentRecommendation)))rows.unshift(currentRecommendation);localStorage.setItem('lm_saved_plans',JSON.stringify(rows.slice(0,20)));renderSavedHub();toast('MY MONTH에 추천을 저장했어요.')}
function deadlineState(d){const now=Date.now(),time=Date.parse(d.start);if(!Number.isFinite(time))return '일정 원문 확인';if(d.kind==='close')return now>time?'기록상 종료 · 원문 확인':'기록상 종료 예정 · 잔여예산 원문 확인';return now<time?'기록상 접수 예정':'접수 예정일 지남 · 현재 상태 원문 확인'}
function programEvidence(d){return regionEvidence(d.region).filter(e=>['A+','A'].includes(e.source_tier)&&((d.title.includes('반값')&&/반값/.test(e.claim+' '+e.source_title))||(d.title.includes('관광주민증')&&/관광주민증/.test(e.claim+' '+e.source_title))))}
function noticeTiming(e,now=new Date()){
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(now);
 const end=e.application_end||'';
 if(e.status==='closed')return {label:'신규 신청 마감',order:-1};
 const parseDate=value=>{
  if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}(?:T\d{2}:\d{2}:\d{2}(?:Z|[+-]\d{2}:\d{2}))?$/.test(value))return null;
  const day=value.slice(0,10),dateOnly=value.length===10,time=Date.parse(dateOnly?day+'T00:00:00+09:00':value);
  const calendar=Date.parse(day+'T00:00:00Z');
  if(!Number.isFinite(time)||!Number.isFinite(calendar)||new Date(calendar).toISOString().slice(0,10)!==day)return null;
  return {day,dateOnly,time};
 };
 const start=e.application_start?parseDate(e.application_start):null,finish=end?parseDate(end):null;
 if((e.application_start&&!start)||(end&&!finish)||(start&&finish&&start.time>finish.time&&(!finish.dateOnly||start.day>finish.day)))return {label:'일정 원문 확인',order:999};
 if(start&&(start.dateOnly?start.day>today:start.time>now.getTime())){
  const when=start.dateOnly?start.day+' · 시작시각 미공개':new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',dateStyle:'medium',timeStyle:'short'}).format(new Date(start.time));
  return {label:'접수 시작 전 · '+when+' 시작 예정 · 원문 확인',order:100};
 }
 if(start?.dateOnly&&start.day===today&&(!finish||finish.dateOnly||finish.time>=now.getTime()))return {label:'오늘 접수 시작 예정 · 시작시각 원문 확인',order:0};
 if(!end)return {label:'일정 미확정 · 원문 확인',order:999};
 const day=finish.dateOnly?finish.day:new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(finish.time)),days=Math.round((Date.parse(day+'T00:00:00+09:00')-Date.parse(today+'T00:00:00+09:00'))/86400000);
 if(!Number.isFinite(days))return {label:'일정 원문 확인',order:999};
 const dateOnly=/^\d{4}-\d{2}-\d{2}$/.test(end);
 const past=dateOnly?day<today:Date.parse(end)<now.getTime();
 const when=dateOnly?day+' · 마감시각 미공개':new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',dateStyle:'medium',timeStyle:'short'}).format(new Date(end));
 return {label:when+' · '+(past?'공고상 마감일 지남 · 상태 재확인':days===0?'오늘 마감 예정 · 원문 확인':days<=7?'D-'+days+' · 마감 예정':'신청 일정')+(!past&&e.early_close_possible?' · 조기 마감 가능 · 접수 상태 원문 확인':''),order:past?998:days};
}
function renderVerifiedNotices(now=new Date()){
 const box=$('#verifiedNotices');if(!box)return;
 const rows=EVIDENCE.filter(e=>['A+','A'].includes(e.source_tier)&&(e.application_start||e.application_end||e.category==='benefit_status'))
 .filter(e=>{const age=(now-Date.parse(e.verified_at+'T00:00:00+09:00'))/86400000;return age>=0&&age<=14})
 .map(e=>({e,t:noticeTiming(e,now)})).sort((a,b)=>a.t.order-b.t.order||a.e.id.localeCompare(b.e.id));
 box.innerHTML=rows.map(({e,t})=>`<article class="source-card verified-notice"><small>${escapeHTML(e.region)} · 확인 ${escapeHTML(e.verified_at)}</small><h3>${escapeHTML(e.source_title)}</h3><p class="program-warning">${escapeHTML(t.label)}</p><p>${escapeHTML(e.claim)}</p><div class="row-actions">${safeURL(e.source_url)?`<a class="btn" href="${safeURL(e.source_url)}" target="_blank" rel="noopener noreferrer">공식 공고 확인 ↗</a>`:''}<button class="btn" data-region="${escapeHTML(e.region)}">지역 근거 보기 →</button></div></article>`).join('')||'<p>최근 확인된 신청 공고가 없습니다.</p>';
}
function renderProgramDesk(){const box=$('#programResults');if(!box)return;const prefs={days:+$('#programDays').value,pet:$('#programPet').value,car:$('#programCar').value,sns:$('#programSns').value};box.innerHTML=DEADLINES.map(d=>{const ev=programEvidence(d),n=escapeHTML(d.region);return `<article class="program-result"><div><small>${n}</small><h3>${escapeHTML(d.title)}</h3><p>${deadlineState(d)}</p><p class="program-warning">${prefs.days}일 체류 · ${prefs.pet==='yes'?'반려견 동반':'반려견 없음'} · ${prefs.car==='yes'?'차량 있음':'차량 없음'} · SNS ${prefs.sns==='ok'?'가능':'피하고 싶음'}</p><ul><li>체류 ${prefs.days}일: 허용·최소 체류일수 원문 확인</li><li>반려견: ${prefs.pet==='yes'?'동반 허용·숙소 조건 원문 확인':'동반 검토 대상 아님'}</li><li>차량: ${prefs.car==='yes'?'차량 보유 입력 · 참가 필수조건 원문 확인':'차량 없이 참가 가능한지·교통 원문 확인'}</li><li>SNS: ${prefs.sns==='avoid'?'의무 미션·면제 여부 원문 확인':'가능 입력 · 게시 횟수·형식 원문 확인'}</li></ul><p>지원 자격: 원문 확인 필요. 현재 자료에는 위 네 조건을 판정할 프로그램별 근거가 없습니다.</p><p>혜택: 1인/팀·실비·조건부 지원금 구조 원문 확인.</p><p>지역 반려견 생활: ${categoryText(d.region,'pet')} (참가 자격과 별도)</p>${d.region.split('·').map(name=>`<button class="btn" data-region="${escapeHTML(name)}">${escapeHTML(name)} 지역 상세 →</button>`).join('')}</div><div class="program-sources"><h4>관련 공식 기록</h4>${ev.length?ev.map(sourceCard).join(''):'<p>연결된 공고 근거 없음 · 원문 확인</p>'}<p class="small">관련 출처가 있어도 개별 조건 확인을 대신하지 않습니다.</p></div></article>`}).join('')||'<p>현재 등록된 공고가 없습니다.</p>'}
function initRC(){$$(".tablewrap").forEach(el=>{el.tabIndex=0;el.setAttribute("role","region");el.setAttribute("aria-label","비교표 · 가로로 스크롤하여 모든 지역 확인")});document.querySelector("#homeRanks")?.closest("section")?.classList.add("internal-only");renderSavedHub();renderPretrip();renderPipelineStatus();if(localStorage.getItem("lm_seen_diff_ids"))ingestDiffNotifications();else localStorage.setItem("lm_seen_diff_ids",JSON.stringify([...(LATEST_DIFF.new||[]).map(x=>`${LATEST_DIFF.current}:new:${x.id}`),...(LATEST_DIFF.changed||[]).map(x=>`${LATEST_DIFF.current}:changed:${x.id}`),...(LATEST_DIFF.removed_or_ended||[]).map(x=>`${LATEST_DIFF.current}:removed:${x.id}`)]));renderNotifications();['savePlan','exportPlan','exportPlanJson'].forEach(id=>$('#'+id).disabled=true);$('#searchBtn').onclick=()=>{const q=$('#searchInput').value.trim();switchPanel('regions');$('#regionDetail').hidden=true;renderRegions('전체',q);renderAll89(q);$('#all89Grid').style.display=q?'grid':'none';$('#toggleAll89').textContent=q?'접기':'89개 보기';$('#regionGrid').scrollIntoView()};$('#searchInput').onkeydown=e=>{if(e.key==='Enter')$('#searchBtn').click()};$('#toggleAll89').onclick=()=>{renderAll89();const open=$('#all89Grid').style.display==='none';$('#all89Grid').style.display=open?'grid':'none';$('#toggleAll89').textContent=open?'접기':'89개 보기'};$('#compareClear').onclick=()=>{state.compare=[];save();refreshSaved()};document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.region)openRegion(b.dataset.region);if(b.dataset.save)toggleSave(b.dataset.save);if(b.dataset.compare)toggleCompare(b.dataset.compare);if(b.dataset.event)toggleEvent(b.dataset.event);if(b.dataset.planRemove!==undefined){const rows=savedPlans();rows.splice(+b.dataset.planRemove,1);localStorage.setItem('lm_saved_plans',JSON.stringify(rows));renderSavedHub()}});$$('.theme').forEach(b=>b.setAttribute('aria-pressed',b.classList.contains('active')));const observer=new MutationObserver(()=>$$('.theme').forEach(b=>b.setAttribute('aria-pressed',b.classList.contains('active'))));$$('.theme').forEach(b=>observer.observe(b,{attributes:true,attributeFilter:['class']}));$$('input,textarea,select').forEach(e=>{if(!e.closest('label')&&!e.getAttribute('aria-label'))e.setAttribute('aria-label',e.placeholder||e.id)});['stayDays','budget'].forEach(id=>$('#'+id).addEventListener('change',()=>invalidateRecommendation()));$$('.theme').forEach(b=>b.addEventListener('click',()=>invalidateRecommendation()));initDrawers();}
function invalidateRecommendation(message='조건이 바뀌었습니다. 추천받기를 다시 눌러 새 결과를 확인하세요.'){
 currentRecommendation=null;
 ['savePlan','exportPlan','exportPlanJson'].forEach(id=>$('#'+id).disabled=true);
 $('#recoResult').innerHTML=`<p>${escapeHTML(message)}</p><button class="btn" onclick="switchPanel('regions')">지역 목록과 출처 보기 →</button>`;
}
function initDrawers(){
 const drawers=$$('.drawer'),openers=new WeakMap(),triggers=new WeakMap(),background=new Map();let active=null;
 for(const [button,drawer]of [['backupBtn','backupDrawer'],['installBtn','installDrawer'],['notifBtn','drawer'],['aboutBtn','aboutDrawer']])$('#'+button).addEventListener('click',()=>triggers.set($('#'+drawer),$('#'+button)),true);
 const isolate=d=>{for(const el of document.body.children){if(drawers.includes(el)||['SCRIPT','STYLE','LINK'].includes(el.tagName)||el.id==='toast')continue;if(d){if(!background.has(el))background.set(el,el.inert);el.inert=true}else if(background.has(el)){el.inert=background.get(el)}}if(!d)background.clear()};
 drawers.forEach(d=>{d.setAttribute('role','dialog');d.setAttribute('aria-modal','true');d.setAttribute('aria-label',d.querySelector('.drawer-head strong')?.textContent||'안내');d.inert=true;new MutationObserver(()=>{
  const open=d.classList.contains('open');d.inert=!open;
  if(open&&active!==d){openers.set(d,active?openers.get(active):triggers.get(d)||document.activeElement);if(active)active.classList.remove('open');active=d;isolate(d);requestAnimationFrame(()=>{if(active===d)d.querySelector('button')?.focus()})}
  else if(!open&&active===d){active=null;isolate(null);requestAnimationFrame(()=>{if(!active)openers.get(d)?.focus?.()})}
 }).observe(d,{attributes:true,attributeFilter:['class']})});
 document.addEventListener('focusin',e=>{if(active&&!active.contains(e.target))active.querySelector('button')?.focus()});
 document.addEventListener('keydown',e=>{if(!active)return;if(e.key==='Escape'){active.classList.remove('open');return}if(e.key==='Tab'){const focus=[...active.querySelectorAll('button,a[href],input,select,textarea,[tabindex="0"]')].filter(x=>!x.disabled&&x.getClientRects().length);if(focus.length){e.preventDefault();const index=focus.indexOf(document.activeElement);focus[(index+(e.shiftKey?-1:1)+focus.length)%focus.length].focus()}}});
}


function validateBackup(payload){
 if(payload?.product!=='LOCAL MONTH'||(payload.schema_version!==undefined&&![1,2].includes(payload.schema_version)))throw new Error('Unsupported backup');
 const storage=payload.storage||(payload.state?{lm_state:JSON.stringify(payload.state)}:null);
 if(!storage||Array.isArray(storage)||typeof storage!=='object')throw new Error('Missing storage');
 const approved=new Set(['lm_state','lm_prefs','lm_saved_plans','lm_hadong','lm_pretrip','lm_device_qa','lm_seen_diff_ids']);
 const out={};for(const [key,value]of Object.entries(storage)){if(!key.startsWith('lm_')||typeof value!=='string')throw new Error('Invalid value');if(key==='lm_schema_version'){if(!['1','2'].includes(value))throw new Error('Invalid schema')}else if(approved.has(key)&&!validStoredValue(key,JSON.parse(value)))throw new Error('Invalid record');
 out[key]=value;}if(!Object.keys(out).length)throw new Error('Empty backup');return out;
}
function restoreLocalData(event){const file=event.target.files?.[0];if(!file)return;if(file.size>5*1024*1024){toast('백업 파일은 5MB 이하여야 합니다.');event.target.value='';return}const reader=new FileReader();reader.onload=()=>{try{const incoming=validateBackup(JSON.parse(reader.result));if(!confirm('백업에 포함된 기록을 복원할까요? 같은 항목은 덮어쓰고, 백업에 없는 기록은 유지합니다. 현재 기록을 먼저 백업해 주세요.'))return;applyBackup(incoming);location.reload()}catch{toast('백업 형식 또는 저장 공간을 확인해 주세요. 현재 기록은 유지했습니다.')}finally{event.target.value=''}};reader.onerror=()=>{toast('백업 파일을 읽지 못했습니다.');event.target.value=''};reader.readAsText(file)}

function exportCurrentPlanICS(){if(!currentRecommendation)return toast('먼저 추천을 실행하세요.');const d=new Date(),start=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())),format=x=>x.toISOString().slice(0,10).replaceAll('-','');const end=new Date(start);end.setUTCDate(end.getUTCDate()+currentRecommendation.days);const stamp=new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d+Z/,'Z');downloadText(`LOCAL_MONTH_${currentRecommendation.top.region}.ics`,['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//LOCAL MONTH//Stay Plan//KO','BEGIN:VEVENT',`UID:${Date.now()}@local-month`,`DTSTAMP:${stamp}`,`DTSTART;VALUE=DATE:${format(start)}`,`DTEND;VALUE=DATE:${format(end)}`,`SUMMARY:${escICS(currentRecommendation.top.region+' 체류 계획 초안')}`,`DESCRIPTION:${escICS('오늘부터 '+currentRecommendation.days+'일로 만든 계획 초안입니다. 출발일은 캘린더에서 변경하세요. 실제 예약·행사 일정이 아닙니다.')}`,'END:VEVENT','END:VCALENDAR',''].join('\r\n'),'text/calendar')}


function isCorrectedBenefit(e){return e.category==='benefit'&&/관광주민증/.test(e.claim+' '+e.source_title)&&/이벤트|쿠폰/.test(e.claim)}
function liveEvidence(e){return ['A+','A'].includes(e.source_tier)&&!isCorrectedBenefit(e)&&['active','policy','infrastructure','recent'].includes(e.status)&&evidenceAgeState(e.verified_at).label==='최신'}
function sourceCard(e){return `<article class="source-card"><p>${escapeHTML(e.claim)}</p>${isCorrectedBenefit(e)?'<p class="program-warning">2026-10-06 정정 기록: 관광주민증 권역 이벤트 쿠폰은 예산소진·사용종료. 이 과거 안내를 현재 혜택으로 판단하지 마세요.</p>':''}<small>${escapeHTML(e.source_tier)} · 기록 확인일 ${escapeHTML(e.verified_at)} · ${evidenceAgeState(e.verified_at).label} · ${e.status==='unconfirmed'?'접수·자격 원문 확인':escapeHTML(e.status)}</small>${safeURL(e.source_url)?`<a class="btn" href="${safeURL(e.source_url)}" target="_blank" rel="noopener noreferrer">${escapeHTML(e.source_title)} ↗</a>`:'<span>원문 확인 필요</span>'}</article>`}
function renderBenefits(){$('#benefitList').innerHTML='<p>혜택 기록은 실시간 잔여예산을 보장하지 않습니다. 관광주민증 권역 이벤트 쿠폰은 2026-10-06 정정 기록상 예산소진·사용종료입니다.</p>'+BENEFITS.map(b=>`<article class="source-card"><h3>${escapeHTML(b.region)} · ${escapeHTML(b.name)}</h3><p>이용 가능 여부·실제 환급액: 원문 확인</p><button class="btn" data-region="${escapeHTML(b.region)}">지역 근거 확인 →</button></article>`).join('')}

window.rcLoaded=true;window.dispatchEvent(new Event('rc-loaded'));
